### ISSUE TITLE
How can I change the amount of monitors?

### ISSUE THREAD

**Issue by sjempotje** [ge9/IddSampleDriver#11]
Hello ge9,

I want to use your really helpfull tool but there is onething I want: Can I only have 1 virtual monitor instead of 5?
I couldn't find it anywhere? Would really like it if you could help me.

yours sincerely,
sjempotje

**Comment by ge9** [comment]
Are you really using my fork?  Download it [here](https://github.com/ge9/IddSampleDriver/releases).
My [option.txt](https://github.com/ge9/IddSampleDriver/blob/master/option.txt) has only one display by default (specified by the first line).

**Comment by sjempotje** [comment]
Yes, but I fixed it with a restart of my machine.
Thx for the help and sorry for my late response.
Happy xmas!
