### ISSUE TITLE
Can not use it to connect to Moonlight or Anydesk

### ISSUE THREAD

**Issue by PaleNeutron** [ge9/IddSampleDriver#18]
I found it does not work for Moonlight or Anydesk. These program is why I need this instead of using RDP. Windows disable GPU when using rdp.

**Comment by k8188219** [comment]
I tried Anydesk and it works. I can view the virtual monitor.

**Comment by PaleNeutron** [comment]
It's my mistake, it works with Anydesk. Moonlight seems need a virtual monitor hardware to activate Nvidia GPU.
