### ISSUE TITLE
How to enable HDR?

### ISSUE THREAD

**Issue by fai2523** [ge9/IddSampleDriver#21]
Is there any way for me to turn on HDR so that it work with moonlight streaming.

**Comment by yenba** [comment]
Also curious about this!

**Comment by yenba** [comment]
It looks like Microsoft added support for HDR to the indirect display driver! https://learn.microsoft.com/en-us/windows-hardware/drivers/display/iddcx1.10-updates.

**Comment by ge9** [comment]
discussed at  https://github.com/roshkins/IddSampleDriver/issues/23

**Comment by ge9** [comment]
supported by https://github.com/itsmikethetech/Virtual-Display-Driver
