### ISSUE TITLE
Warning: Malware. Destroys everything

### ISSUE THREAD

**Issue by anderse77** [ge9/IddSampleDriver#29]
Followed the instructions to the letter. Now my computer won't boot. Only shows on this display and every other display is black. Monitor won't show up in nvidia control panel. DO NOT DOWNLOAD FOR WHATEVER REASON. EVERYONE SAYING THIS WORKS IS LYING!!!

**Comment by FangLecheng** [comment]
愚蠢的人！你设置了仅在此显示器显示，其它显示器当然是黑屏状态，电脑屏幕想要恢复只需要连续按两次win＋p，你完全没明白这个软件是有什么作用

**Comment by anderse77** [comment]
No problem is it attached to it's own adapter and monitor is not accelerated by my Rtx 4090 card. I want to use it for moonlight. You are the stupid person who does not undersand what i am saying.

**Comment by kersplash-wav** [comment]
Computer should boot up fine, what the other person was saying is that you might need to switch primary monitor on welcome screen to your physical one.
