### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by Gissio** [ge9/IddSampleDriver#33]
It seems `Virtual_Display_Driver.cer` expired on 14/10/2024, which makes Windows refuse to load IddSampleDriver. Please help!

**Comment by ge9** [comment]
It's 14/10/20**3**4, isn't it? And you have to register the certificate to the Windows certificate store.

**Comment by Gissio** [comment]
My bad! The certificate had in fact expired, but I was using a different `IddSampleDriver`, not yours! With your release everything is working now.

Sorry for the mistake. And thanks for your work!
